### ISSUE TITLE
cannot get the dividend distributed immediately

### ISSUE THREAD

**Issue by lixianbin1** [PolymeshAssociation/polymesh-sdk#893]
When I use "identity.getPendingDistributions" queries the dividend sent to me, it cannot get the dividend distributed immediately

**Comment by F-OBrien** [comment]
Can you clarify what you mean by "immediately"?

After a dividend distribution instruction is sent you need to wait for the transaction to be processed on chain before it will be possible to read pending distributions. Polymesh has a 6 second block time, if the chain was congested it may take longer than this before the distribution is available to claim on chain.

**Comment by lixianbin1** [comment]
After executed "distribution. pay()" , switched to the receiving account, I executed "identity.getPendingDistributions()" I did not find incoming distribution

**Comment by lixianbin1** [comment]
Well, I waited for two hours.  the chain was congested ?

**Comment by F-OBrien** [comment]
The problem here is after you call `distribution.pay()` you no longer have a pending distribution. The `pay` method pushes the dividend to the recipient hence completes the pending distribution. You can call `identity.getPendingDistributions` before it is pushed and in that case can call the `claim` method instead of waiting for the issuer to `pay`  it.

If you still have questions please provide full list of steps performed and links to the applicable transactions in the blockchain explorer.

I checked the testnet blockchain explorer and see multiple instances of dividend distributions being created and multiple instances of the benefits being pushed successfully to the recipient after creation.

**Comment by lixianbin1** [comment]
@F-OBrien  I think I can roughly understand that after the execution of pay, the recipient does not need to execute a claim, and the dividend will go to the recipient's portfolio,Thank you very much for your help.

**Comment by F-OBrien** [comment]
@lixianbin1 you're welcome. If you have any general questions please feel free to reach out to us through the developer channels on discord https://discord.gg/ud2deWAnyt
