### ISSUE TITLE
The asset does not exist

### ISSUE THREAD

**Issue by lixianbin1** [PolymeshAssociation/polymesh-sdk#895]
I used getClaimScopes to query data, and then used getAsset to query LXB2, but I was prompted that the data does not exist. But the test website seems to have queried the data.

![image](https://user-images.githubusercontent.com/22391220/204240067-fd030e65-b33a-4259-8f8e-885df4aa8cde.png)

This identity is 0xa39bd22fd2f078fd1c300614f564dda94a90ad3884601677fb3042b591dbede2
This Asset is LXB2

**Comment by F-OBrien** [comment]
Identity 0xa39bd22fd2f078fd1c300614f564dda94a90ad3884601677fb3042b591dbede2 has been assigned a claim scoped to the token `LXB2` so under the list of claims for that **identity** it shows those details and `getClaimScopes` returns the claims correctly. However, just because the claim issuer assigned a claim scoped to the `LXB2` token it does not mean that token exists on chain. In this case the asset `LXB2` has not yet been registered or created on chain so `getAsset` correctly errors saying the data does not exist.

**Comment by lixianbin1** [comment]
OK,I see. The claim does not mean that the asset exists
