### ISSUE TITLE
How to obtain "Corporate Action" entities

### ISSUE THREAD

**Issue by ty-zyp** [PolymeshAssociation/polymesh-sdk#899]
I've been searching for a long time, but I haven't found a way to get the corporate action entity

**Comment by F-OBrien** [comment]
@ty-zyp The corporate actions entity can be got from an asset. So you first need to get the asset entity before you can manage corporate actions with the SDK. e.g. 
`const asset = await polymeshSdk.assets.getAsset({ticker:'ACME'});`
https://github.com/PolymeshAssociation/polymesh-sdk/wiki/api.entities.Asset.Asset

For general question I'd recommend you using discord instead of creating issues. https://discord.gg/ud2deWAnyt
